version: "3.8"
volumes:
  app:
  db-laravel-practice-data:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - app:/docker-practice
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=products
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db-laravel-practice-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-products}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
