version: "3.8"
volumes:
  app:
  db-laravel-practice-data:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - app:/docker-practice
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=products
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "33306:3306"
    volumes:
      - db-laravel-practice-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=secret
